### ISSUE TITLE
[Request] Please add a simple kiosk/fullscreen mode for v1

### ISSUE THREAD

**Issue by Conan-Kudo** [BuddiesOfBudgie/magpie#18]
### Magpie version

1.0~git20231126.e106dfe

### Use-cases

For the Fedora Budgie spin, we need a way for the Budgie Wayland compositor to be able to run an application full screen for two particular reasons:

1. To function as the compositor for a login manager greeter (e.g. SDDM, greetd, etc.)
2. To be able to run [Anaconda Initial Setup](https://github.com/rhinstaller/initial-setup)

Without this ability, we would be forced to ship two compositors on the spin, which is certainly not great.

### Proposal

I would suggest somewhat mimicking KWin's mechanism for this by providing a flag for launching Magpie with a single application and to automatically shut down when that application quits and forward that application's exit code. This makes it very easy to support single-application use-cases. Failing that, some kind of way to have an alternate configuration file that lets you tell the compositor you are launching a single application and then quitting after it exits would work too.

### References

* [KDE Plasma's SDDM configuration to use KWin](https://invent.kde.org/plasma/plasma-workspace/-/blob/master/sddm-wayland-session/plasma-wayland.conf)
* [Fedora KDE's stub to use KWin for `initial-setup-gui`](https://pagure.io/fedora-kde/kde-settings/blob/rawhide/f/usr/libexec/initial-setup/run-gui-backend)
* [Fedora Sway's SDDM configuration to use Sway](https://gitlab.com/fedora/sigs/sway/sway-config-fedora/-/tree/fedora/sddm)
* [Fedora Sway's stub to use Sway for `initial-setup-gui`](https://gitlab.com/fedora/sigs/sway/sway-config-fedora/-/blob/fedora/initial-setup/run-gui-backend)
* [Anaconda Initial Setup's stub to use Weston for `initial-setup-gui`](https://github.com/rhinstaller/initial-setup/blob/master/scripts/run-gui-backend.guiweston)

**Comment by serebit** [comment]
As far as I'm concerned, it's up to the application to size its surfaces properly and avoid decorations. I can easily add an option to attach to the lifecycle of a subprocess, though.

**Comment by serebit** [comment]
Fixed with #18. I don't know why Fedora CI is exploding, Alpine is fine and it works on my Arch machine.
