### ISSUE TITLE
[Bug] Segfault when using virtualbox without 3D host graphics

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/magpie#24]
### Description

magpie-wm immediately crashes.  the gdb trace file crashes at this point https://github.com/BuddiesOfBudgie/magpie/blob/9af5081579321e23528a7466b454694319b68974/src/server.cpp#L387

Switching virtualbox to using 128Mb graphics + 3D acceleration allows magpie-wm to launch successfully

### Magpie version

v1 9af5081579321e23528a7466b454694319b68974

### Operating System

ubuntu budgie 24.04

### Steps to reproduce the issue

SDDM.  use budgie-wayland-session budgie-desktop-wayland desktop file to launch magpie-wm. Not using the magpie-wm.conf file

### Actual result

segfault as per the description

[output.txt](https://github.com/user-attachments/files/15747623/output.txt)

### Expected result

startup success.

**Comment by serebit** [comment]
Updated the code to exit gracefully instead of segfaulting when a renderer can't be created. I'll have to investigate further to see why the renderer can't be created, though - wlroots *should* support rendering via pixman.

**Comment by serebit** [comment]
Closing this as wontfix - if wlroots did support rendering via pixman at one point, it doesn't anymore. I spun up a virtualbox VM with no attached graphics and no wlroots-based compositor that I tried managed to start up a renderer.
