### ISSUE TITLE
[Bug] segfault when flipping between windows

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/magpie#25]
### Description

[output.txt](https://github.com/user-attachments/files/15854961/output.txt)

https://github.com/BuddiesOfBudgie/magpie/commit/1e45a7d8335250913ff39656c1f35397ed435ef1

opening two windows - just change focus between the two by clicking on their decoration a few times

### Magpie version

latest v1 branch

### Operating System

ubuntu budgie 24.04

### Steps to reproduce the issue

see description

### Actual result

segfault as per output.txt

### Expected result

no segfault

**Comment by serebit** [comment]
Ah, I see the null view in the list of views. That helps a lot with narrowing this down.

**Comment by serebit** [comment]
What did you use for that stack trace?

**Comment by fossfreedom** [comment]
on ubuntu its `apport-retrace -g /var/crash/xyz.crash` to read segfault crash files

**Comment by fossfreedom** [comment]
thx.  looks like its now resolved.  cheers
