### ISSUE TITLE
[Bug] segfault when clicking on icon-tasklist icon to minimise

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/magpie#26]
### Description

After starting an application like Nemo from the menu, clicking on its resultant  icon-tasklist icon leads to a segfault and crash to the login window

apport-retrace -g

[output.txt](https://github.com/user-attachments/files/15937837/output.txt)

### Magpie version

v1 d7adfba77b0cbd681ea381db6562e6e4027bd856

### Operating System

ubuntu budgie 24.04

### Steps to reproduce the issue

see the description

### Actual result

crash as per the description output.txt

### Expected result

minimised window

**Comment by serebit** [comment]
See if fixed with c5c90406c.

**Comment by fossfreedom** [comment]
nicely done!
