### ISSUE TITLE
[Request] Migrate gsettings schema to `org.buddiesofbudgie.magpie`

### ISSUE THREAD

**Issue by eatyourbaby** [BuddiesOfBudgie/magpie#7]
### Magpie version

0.9.2

### Use-cases

Magpie currently shares the same gsettings schema namespace as mutter, i.e. `org.gnome.mutter`. However, if magpie were to co-exist with mutter in an installation, a newer (or older) version of mutter may no longer share the same keys with mutter 43, which might break magpie.

This also offers a solution to #3, as we can add the xrandr fractional scaling patch to magpie as a whole on any distribution.

### Proposal

Migrate gsettings schema away from `org.gnome.mutter` to `org.buddiesofbudgie.magpie`.

**Comment by fossfreedom** [comment]
https://github.com/search?q=org%3ABuddiesOfBudgie%20%22org.gnome.mutter%22&type=code

Thats the sort of change required.

Making a global change like this also will impact other stuff like gnome-remote-desktop that quite a lot of people use.

I haven't look at potentially other GNOME dependencies - need to example gnome-settings-daemon and gnome-session and probably quite a few others as well.

**Comment by eatyourbaby** [comment]
I just learned that Budgie to moving its configuration to TOML. I suppose this won't be an issue when magpie 1.0 releases then.
